version: '3.8'

services:
  twitter-bot:
    container_name: twitter-bot
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/var/log
    environment:
      - TZ=America/Mexico_City