version: '3.8'

services:
  twitter-bot:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/var/log
    networks:
      - twitterbot_net
    environment:
      - TZ=America/Mexico_City