services:
  twitter-bot:
    container_name: twitter-bot
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - twitter_bot_logs:/var/log
    environment:
      - TZ=America/Mexico_City

volumes:
  twitter_bot_logs:
    driver: local